libvncclient/tls_openssl.c

On some systems pthread_mutexattr_settype() and PTHREAD_MUTEX_RECURSIVE are
not available by default.
Either _XOPEN_SOURCE or _POSIX_C_SOURCE needs to be set to to the right level
before including any system include file in order to have them exposed.
Fixes the following compile error, which occurs if you use buildroot to build a rootfs, and have the threading model set to linuxthreads instead of NPTL.
```
tls_openssl.c: In function 'dyn_create_function':
tls_openssl.c:91:2: warning: implicit declaration of function 'pthread_mutexattr_settype' [-Wimplicit-function-declaration]
MUTEX_INIT(value->mutex);
^
tls_openssl.c:42:40: error: 'PTHREAD_MUTEX_RECURSIVE' undeclared (first use in this function)
pthread_mutexattr_settype(&mutexAttr, PTHREAD_MUTEX_RECURSIVE);\
^
tls_openssl.c:91:2: note: …
```

tls_openssl.c: define _XOPEN_SOURCE for extra POSIX functionality

---

libvncclient/rfbproto.c

https://www.gnupg.org/documentation/manuals/gcrypt/Initializing-the-library.html
```Before the library can be used, it must initialize itself.
This is achieved by invoking the function gcry_check_version```
Closes issue #45
Tested with krdc + libgcrypt 1.6.1 (libgcrypt20-dev Ubuntu package)
connecting to a Mac Mini.
Signed-off-by: Floris Bos <bos@je-eigen-domein.nl>

Initialize libgcrypt before use

---

libvncserver/main.c
libvncserver/sockets.c
libvncserver/websockets.c
rfb/rfb.h

- When processing input, check if there is any extra data
pending in the internal websocket frame and SSL buffers.
- Prevents input events lagging behind because they get
stuck in one of the buffers.
Data pending in our own buffers cannot be detected with
select() so was not processed until more input arrives
from the network.
- Closes #55

Fix handling of multiple VNC commands per websockets frame

---

configure.ac

When cross-compiling the ar program has the appropriate prefix prepended.
Respect that here and have autotools autodetect the appropriate tool.

configure.ac: Use AC_CHECK_TOOL for cross-compiling support.

---

libvncserver/rfbssl_gnutls.c
libvncserver/tight.c

When using gnutls to provide TLS for websockets, it's likely to crash in function rfbssl_gc_peekbuf. Also if tight encoding is used and rfbTightCleanup is called, which seems to happen when a client disconnects, the next attempt to use tight encoding will fail, cause j is not reinitialized again.

prevent segfaults due to uninitialized memory

---

libvncclient/rfbproto.c

OS X RealVNC server crashes out Remmina because the server can provoke
bytesPerLine to be zero. Assume this is coding for zero lines.
The condition could be checked before the calculation of bytesPerLine.
I don’t understand the preconditions of this code to say one way or the
other.

Avoid divide-by-zero in raw encoding (OSX RealVNC)

---

libvncserver/httpd.c

Do not process HTTP requests that have .. in the URL.
Provides very basic protection against directory traversal outside of webroot.
In the long run, it might be better to add a more sophisticated check than this.
But that will likely require platform specific code.

httpd: disallow directory traversal

---

rfb/rfbproto.h

They fix endianness detection and an issue with cross builds using Mingw-w64.
Those cross builds are still broken because of other issues.

Fix some recently introduced regressions

---

examples/camera.c

The camera.c example application would sometimes crash due to a memset outside the allocated memory.

Fix memory access error in camera.c example

---

libvncclient/rfbproto.c

Whenever as a result of encodings passed in the client extensions the overall number of encodings exceeded MAX_ENCODINGS, a buffer overflow would occur.

Fix buffer overflow when applying client encodings

---

libvncserver/rfbserver.c
libvncserver/sockets.c

I am bulding a docker vncterm using libvncserver, works with openstack nova-docker driver.
Due to the firewall access control list, I can only listen on a single port. So I use a proxy in front of docker vncterms. The proxy connects to vncterms using AF_UNIX socket (In each compute node, we runs over 1000+ containers, and multiple vncservers can be launched for each container. It may requires lots of TCP ports. It's much easier to use AF_UNIX socket, I just create a unique path, I don't needs to probe and auto allocate TCP ports).
Checking setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one) and exit prevents it from working, so I ignore the errors.

Enable AF_UNIX socket: ignore setsockopt TCP_NODELAY failure.

---

libvncclient/tls_gnutls.c
libvncclient/vncviewer.c
rfb/rfbclient.h

Fix upstream issue #100
Squashed commit of the pull request #101 :
commit 1c7e01e81862bc46508e675e83c74cc6d63224b0
commit 1e749b094d6696380d3f0540a00138d7e3427874

libvncclient/tls_gnutls.c: Add hooks to WriteToTLS() for optional protection by mutex. (Squashed)

---

libvncclient/listen.c
libvncserver/httpd.c
libvncserver/rfbserver.c
libvncserver/sockets.c
rfb/rfbproto.h

Not using generic 'max', avoids conflicts with stl_algobase.h
The macro was previously not used on WIN32/MINGW32 apparently , so someone with more experience with building for those platforms may want to double-check this.

use namespaced vnc_max macro (issue #102)

---

libvncserver/sockets.c

Avoid calling SSL_pending when connection is already closed, calling SSL_pending with connection already closed is crashing. 
To reproduce, open a secure websocket binay protocol connection with libvncserver compiled with OpenSSL, and when libvncserver is waiting for rfbProcessClientProtocolVersion send any invalid char, it will fail and call rfbCloseClient whith destroy all SSL context, calling SSL_pending after that will generate a invalid access.

Avoid calling SSL_pending when connection is already closed

---

libvncserver/sockets.c

Make it possible to get autoPort behavior with either ipv4 or ipv6
disabled, by setting rfbScreen->ipv6port or rfbScreen->port to a
negative number. This will make it possible for x11vnc to enforce
its -noipv6 option, as discussed in the following bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=672449

Support autoPort with ipv4 or ipv6 disabled

---

libvncclient/rfbproto.c
libvncclient/ultra.c

This PR fixes two unrelated buffer overflows, which can be used by a malicious server to overwrite parts of the heap and crash the client (or possibly execute arbitrary code). 
PoC (for `./client_examples/gtkvncviewer`):
```
#! /usr/bin/env python3
import asyncio
import struct
import lzo
import time
class EvilVNCProtocol(asyncio.Protocol):
def connection_made(self, transport):
self.transport = transport
self.transport.write(b"RFB 003.008\n")
self.transport.write(b"\x01\x01")
self.transport.write(b"\x00\x00\x00\x00")
self.transport.write(
struct.pack(">HHBBBBHHHBBBBBBIB",
100, 100, # Framebuffer width and height
32, # Bits per pixel
8, # Color depth
1, # Big endian
1, # True Color
255, 255, 255, # Color max values
0, 8, 16, # Color shifts
0, 0, 0, # Padding
1, # Name length
ord("E") # Name …
```

Fix two heap buffer overflows

---

test/Makefile.am

The new jpeg tests were added to noinst when they should have been
under check like all the other programs in here.

test/Makefile: use check_PROGRAMS

---

libvncserver/websockets.c

When testing with noVNC and Chrome, noVNC did not include Sec-WebSocket-Protocol in the request header, so Chrome threw an error indicating it should not have received Sec-WebSocket-Protocol in the libvncserver response.

Sec-WebSocket-Protocol header fix

---

libvncclient/tls_openssl.c

These patches should fix support for the OpenSSL 1.1.x branch.

Openssl 1.1.x support

---

libvncclient/corre.c
libvncclient/hextile.c
libvncclient/rfbproto.c
libvncclient/rre.c
libvncclient/tight.c
libvncclient/ultra.c
libvncclient/vncviewer.c
libvncclient/zlib.c
libvncclient/zrle.c
rfb/rfbclient.h

These changes make it possible for the application to handle all of the rendering and JPEG decoding, thus allowing GPU accelerated rendering and multi-core decoding. I'm using this on a Raspberry Pi 2 where the CPU is not powerful enough to handle VNC.

Add function pointers for every type of rectangle

---

libvncserver/font.c

Fixes a tiny leak case. The file handle wouldn't be closed in this instance.

font: Fix a small resource leak in a failure case in rfbLoadConsoleFont()

---

libvncclient/tls_openssl.c
rfb/rfbclient.h

This change adds X509 certificate validation to libvncclient when built with OpenSSL.  It's basically the OpenSSL equivalent of pull request 175 and supports the following:
1. Verification of server certificate against either a specified CA or the CA certificates in the default directory.
2. Sending a client certificate or chain to the server for checking
3. Specification of a CRL either in a separate file (as per the existing callback) or appended to the CA file as is the norm for OpenSSL, or in the default directory.
4. A new field in the callback specifying whether all certificates in the server chain will be checked or only the server certificate itself.  This is useful with OpenSSL because, unlike GnuTLS, if the whole chain is to be checked it requires a CRL for every certificate (an …

X509 certificate verification for OpenSSL

---

libvncclient/tls_gnutls.c

This is a simple change that implements server X509 certificate verification in libvncclient when built with GNU TLS.  It was left TODO in the original implementation.   The approach taken is to integrate the verification into the handshake process so that success or failure of the negotiation and the decision to continue is in one place in the code rather than scattered.
The change has been tested with a few failure scenarios including a server that doesn't match the certificate it provides, and an untrusted certificate chain.

Added support for X509 server certificate verification

---

libvncserver/websockets.c

gtk-vnc 0.7.0 ships with a little [trick](https://git.gnome.org/browse/gtk-vnc/commit/?id=7f4f2fe8da72ed9fef5dd4319e19feb2b4f3d62e) that prevents erroneous connections from VNC clients to SPICE servers from hanging indefinitely.  The trick is to send 4 out of 12 bytes comprising the [*ProtocolVersion Handshake*](https://tools.ietf.org/html/rfc6143#section-7.1.1) without waiting for the server to send anything and only send the remaining 8 bytes after receiving the *ProtocolVersion Handshake* from the server.  However, if libvncserver asserts there is data waiting to be read from a connected socket before it sends its *ProtocolVersion Handshake*, it assumes it is not a normal VNC connection and attempts to detect what it is talking to.  As `"RFB "` is not among the options it checks, all …

websockets: Ensure compatibility with gtk-vnc 0.7.0+

---

CMakeLists.txt
common/base64.c
common/base64.h
libvncserver/websockets.c
libvncserver/ws_decode.c
libvncserver/ws_decode.h

Websockets support depends on base64 functions (`__b64_ntop` and `__b64_pton`). However, on some systems, these functions are not provided by libc nor libresolv.  An example of a such system is the `alpine` distro, which uses the `musl` libc implementation.
So to be able to support these systems, a simple change can be done: If base64 functions are not provided by any library, compile the local implementation of these functions along with websocket code.

websockets: Fixed compilation of websockets on systems where there is no implementation of base64 functions.

---

.appveyor.yml
CMakeLists.txt
client_examples/ppmtest.c
libvncclient/rfbproto.c
libvncclient/rfbsasl.c
libvncclient/rfbsasl.h
libvncclient/sockets.c
libvncclient/tls.h
libvncclient/tls_gnutls.c
libvncclient/tls_none.c
libvncclient/tls_openssl.c
libvncclient/vncviewer.c
rfb/rfbclient.h
rfb/rfbconfig.h.cmakein
rfb/rfbproto.h

This change adds SASL authentication support to libvncclient.
By default SASL support is disabled and needs to be enabled in the build with -DWITH_SASL=YES.  It relies on libsasl2 from Cyrus SASL for the actual SASL implementation.  The bulk of the code is taken from the GTK VNC viewer.

Add SASL authentication support to libvncclient

---

libvncclient/zrle.c

If zlib is not available (probably should be available but...) we get issue #214 
This PR simply moves the undef of REALBPP outside of the ifdef that checks for zlib causing it to properly undefine.

Moved undef of REALBPP down

---

libvncserver/tight.c
rfb/rfb.h

These functions can be used to send already compressed jpegs to a
client, circumventing the usual rect/region update methods which
operate on a raw rgb framebuffer. Rename the functions with the usual
rfb prefix and add the prototypes in rfb.h.

Tight: export SendCompressedData and SendTightHeader functions

---

libvncclient/vncviewer.c

Buffers allocated by encoding handlers have to be freed as well.

LibVNCClient: free buffers in rfbClientCleanup()

---

common/d3des.c
common/d3des.h
libvncclient/rfbproto.c

One more PR... The current D3Des implementation is not thread safe as it operates on a global array for the DES key register. Adding compiler-specific attributes for TLS fixes the issue.

Make D3DES thread safe + minor fixes

---

libvncserver/tight.c
libvncserver/zlib.c

The TLS macro never has been defined due to the missing
LIBVNCSERVER_HAVE_TLS macro. This revises the macro logic to also cover
Win32 builds with MSVC.

LibVNCServer: properly use thread-local storage

---

.travis.yml
CMakeLists.txt
cmake/Modules/FindLZO.cmake
libvncclient/rfbproto.c
libvncserver/ultra.c
rfb/rfbconfig.h.cmakein

The complete LZO library nowadays is installed on many systems so we can
optionally make use of it and omit internal miniLZO implementation.

Allow to use global LZO library instead of miniLZO

---

libvncserver/main.c
libvncserver/rfbserver.c
rfb/rfb.h

- Correctly iterate over the clients without using freed memory. (See #211)
- Fix a concurrent issue between the thread doing the shutdown that will free the client and the thread of `clientOutput` that will access it.
See #212 for more informations.
**PS:** It's really hard to make a tiny PR because of the indentation issues everywhere, you should probably do something about that :)

Fix use-after-free and concurrent access segmentation fault

---

libvncclient/rfbproto.c

Fixes warning with GCC 8:
rfbproto.c: warning: ‘strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]
strncpy((char *)username, cred->userCredential.username, sizeof(username));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rfbproto.c: warning: ‘strncpy’ specified bound 64 equals destination size [-Wstringop-truncation]
strncpy((char *)password, cred->userCredential.password, sizeof(password));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LibVNCClient: fix potentially missing null byte

---

libvncserver/main.c

client_thread is created depending upon backgroundLoop, but joining
without checking for same condition. so we are trying to join a garbage
thread_id.

avoid pthread_join if backgroundLoop is FALSE

---

libvncserver/ws_decode.c

See https://bugs.gentoo.org/686914
It crashes in wstest otherwise.
It should not hurt on platforms that support unaligned accesses as the compiler usually is clever enough to optimize memcpy() away.

fix crash because of unaligned accesses in hybiReadAndDecode()

---

libvncserver/rfbserver.c

Commit cedae6e6f97b14f5df3ea7c5f7efd59f2bc9ad82 introduces a pipe fd pair (pipe_notify_client_thread) to rfbClientRec. These fd's are created only in the "background loop" operation mode. Otherwise they are incorrectly left as zero. In effect, rfbClientConnectionGone closes fd 0 (twice), causing lots of problems later on.
This commit fixes the issue by properly intializing the unused fd's to -1

rfbserver: don't close fd 0 accidentally

---

libvncserver/rfbserver.c
rfb/rfb.h

This commit adds a hooking function to deliver
rfbFramebufferUpdateRequest messages from clients to the frame
producer for a case the producer needs to handle the messages for
flow control or etc.
This change is for OpenBMC KVM feature in:
https://github.com/openbmc/openbmc
Resolves this issue:
https://github.com/openbmc/bmcweb/issues/80

rfbserver: add a hooking function to deliver rfbFramebufferUpdateRequest messages

---

libvncclient/rfbproto.c

Inverting a bitmask should be done using a bitwise NOT instead of a
logical NOT.

rfbproto: invert bitmask using bitwise NOT

---

libvncclient/trle.c

Fixes compiler warnings:
In file included from libvncserver/libvncclient/rfbproto.c:2390:
libvncserver/libvncclient/trle.c: In function 'HandleTRLE8':
libvncserver/libvncclient/trle.c:128:11: warning: 'color' may be used uninitialized in this function [-Wmaybe-uninitialized]
client->GotFillRect(client, x, y, w, h, color);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libvncserver/libvncclient/trle.c:145:54: warning: 'divider' may be used uninitialized in this function [-Wmaybe-uninitialized]
(w + divider - 1) / divider * h))
~~~~~~~~~~~~~~~~~~^~~~~~~~~
libvncserver/libvncclient/trle.c:153:50: warning: 'mask' may be used uninitialized in this function [-Wmaybe-uninitialized]
palette[((*buffer) >> shift) & mask];
~~~~~~~~~~~~~~~~~~~~~^~~~~~
libvncserver/libvncclient/trle.c:154:23: warning: …

trle: add missing variable initializations

---

libvncclient/tls_openssl.c

The typedef for MUTEX_TYPE fails if pthread_mutex_t is not defined
through pthread.h before.

LibVNCClient: tls_openssl: include pthread.h early

---

libvncserver/rfbserver.c
libvncserver/zrle.c

Local header files shouldn't be included as system header files.

LibVNCServer: fix inclusion of own headers

---

libvncclient/tight.c

Introduced by d7b1462 in LibVNCServer 0.9.12.  This regression caused
the pixels in some RFB rectangles to become corrupted/garbled when the
Tight encoding was used, without the JPEG subencoding, with a 15-bit or
16-bit color depth.
Fixes #335
Fixes https://gitlab.com/Remmina/Remmina/issues/1824

LibVNCClient: Fix regression in Tight/Raw decoding

---

libvncserver/websockets.c

The WebSocket specification does not include base64 encoding. It was mentioned in a very early draft of the specification but never made it to any final version.
Not many WebSocket clients out there support base64 data, and the ones that do are very outdated.
Then there's the topic of subprotocols - Currently, libvncserver requires a client to specify 'binary' as a subprotocol in order to not get base 64 data. To have this subprotocol value is also not valid according to the WebSocket standard.
With this PR the code will still be compatible with old clients that specifically ask for 'binary' or 'base64' using subprotocols. (Even if subprotocols shouldn't actually be used to determine the main encoding that is used for the data on the WebSocket.)

Use binary encoding as default instead of base64

---

rfb/rfbproto.h

It's definitely wrong to build with LIBVNCSERVER_WORDS_BIGENDIAN
defined on Win32. Instead use the auto-detected endianess macro
(which will indicate little endian on i686/x86_64). Removing the
hardcoded define makes all tests pass (especially encodingtest)
when built with the MinGW64 toolchain.
In combination with PR #257 this fixes issues #165 and #249.

rfbproto: fix broken endianess handling on Win32

---

libvncserver/main.c

Otherwise the servers that don't use rfbRunEventLoop don't get
notified of client disconnections

rfbShutdownServer: Call rfbClientConnectionGone if no backgroundLoop

---

examples/repeater.c
libvncclient/listen.c
libvncclient/rfbproto.c
libvncclient/sasl.c
libvncclient/sockets.c
libvncclient/tls_gnutls.c
libvncclient/vncviewer.c
libvncserver/httpd.c
libvncserver/main.c
libvncserver/rfbserver.c
libvncserver/sockets.c
rfb/rfb.h
rfb/rfbclient.h
rfb/rfbproto.h

The Windows Sockets 2 API uses the type SOCKET for all functions and is
defined as an unsigned integer with an architecture-specific width.
Storing the result of WS2 functions in an integer field is therefore
insufficient and may lead to a wrong behaviour. Additionally invalid
sockets are not represented by negative numbers but the constant
INVALID_SOCKETS.

Use platform-specific type for socket FDs

---

libvncclient/rfbproto.c

This amends 1f6da568b27629c6da1d6b356e430f4e0be3d3ee.

rfbproto: add missing RFB_INVALID_SOCKET

---

libvncclient/rfbproto.c

The IPv4 code which is used as fallback contains calls to deprecated
network functions such as gethostbyname() which are not thread-safe
and thus can lead to crashes when called in multiple threads at the
same time. The IPv6 code properly uses getaddrinfo() which does not
suffer from these problems. When IPv6 is enabled the modern code
paths should be used exclusively. It's unlikely anyway that the
legacy network code succeeds after IPv6 (which is capable of
establishing IPv4 connections as well) failed before.
Closes #262.

libvncclient: rfbproto: do not fallback to IPv4

---

common/crypto_openssl.c

This fixes compatibility with OpenSSL 1.1.0 and adds a missing header for `RAND_bytes()`

Minor OpenSSL compatibility fixes

---

common/vncauth.c
libvncserver/main.c

The following two commits are required to successfully build libvncserver for a Windows project on my site:
* vncauth: include RFB headers first
* libvncserver: include sys/time.h if available

Fix headers

---

libvncserver/rfbserver.c

As of e1d06824e7a957bf483a81903bc8a19d89414492 for Windows builds read() is properly
wrapped to recv() which takes a signed char array. Since we cast the
pointer to signed char for other function calls as well we can make it
a signed char array right from the start.
Fixes compiler warning/error:
```
libvncserver/libvncserver/rfbserver.c: In function ‘rfbSendFileTransferChunk’:
libvncserver/libvncserver/rfbserver.c:1549:51: error: pointer targets in passing argument 2 of ‘recv’ differ in signedness [-Werror=pointer-sign]
bytesRead = read(cl->fileTransfer.fd, readBuf, sz_rfbBlockSize);
^~~~~~~
libvncserver/common/sockets.h:51:38: note: in definition of macro ‘read’
#define read(sock,buf,len) recv(sock,buf,len,0)
^~~
In file included from libvncserver/rfb/rfbproto.h:68,
from …
```

rfbserver: make readBuf a signed char array

---

libvncclient.pc.cmakein
libvncserver.pc.cmakein

Remove zlib from Requires.private as libvnc can be built without zlib
thanks to WITH_LIB, zlib will be added to Libs.private thanks to
PRIVATE_LIBS
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

libvnc{client,server}.pc.cmakein: remove zlib

---

libvncserver/sockets.c

Don't print an uninitialized string

---

libvncclient/tls_gnutls.c
libvncclient/tls_openssl.c

rfb: Fix for missing stdio.h include (and hence undeclared snprintf).

Fix for missing stdio.h include needed for iOS

---

libvncclient/tls_openssl.c

OpenSSL TLS context cannot be used for concurrent reading & writing from different threads. This was already reported in #100 . PR #118 fixes it for GnuTLS. 
I am facing the same issue with  LibreSSL & MultiVNC.
This PR wraps TLS read/write operations inside a mutex.

Fix multithreaded read/write with TLS for OpenSSL.

---

libvncclient/rfbproto.c
libvncclient/sockets.c
libvncclient/vncviewer.c
rfb/rfbclient.h

Depending on the platform and the TCP/IP stack configuration connect()
can block for a very long time if the destination host is unreachable.
The current behaviour blocks VNC client loops for an uncertain amount of
time. However some applications may want to implement responsive VNC
client threads requiring rfbInitClient() to time out more quickly. This
can be achieved by calling connect() on a non-blocking socket and
select() with a timeout afterwards. The new WaitForConnected() function
deals with the platform-specific behaviour of this mechanism.

LibVNCClient: add connect timeout support

---

libvncclient/sockets.c
libvncclient/vncviewer.c
rfb/rfbclient.h

When a connection is not reset properly at the TCP level (e.g. sudden power loss or process crash) the TCP connection becomes half-open and read() always returns -1 with errno = EAGAIN while select() always returns 0. This leads to an infinite loop and can be fixed by closing the connection after a certain number of retries (based on a timeout) has been exceeded.

libvncclient: handle half-open TCP connections

---

libvncclient/tls_gnutls.c
libvncclient/tls_openssl.c
rfb/rfbclient.h

I have added a comment to indicate its internal use but to allow this type of modifications in future we could create a separate 'internal' structure.

Add TLS R/W mutex to rfbClient

---

libvncserver/corre.c
libvncserver/rre.c
libvncserver/tight.c
libvncserver/ultra.c
libvncserver/zlib.c
libvncserver/zrleoutstream.c

When realloc() fails, previous pointer values have to be retained to leaking memory.

Handle memory realloc failures

---

libvncserver/rfbserver.c

Some minor fixes:
backgroundLoop != FALSE -- means true
missed `screen->backgroundLoop` check in case of LIBPTHREAD defined in rfbClientConnectionGone()

add missed screen->backgroundLoop check

---

libvncserver/zlib.c

The pointers to the buffers were freed, and the size fields were set to
0, but the buffer pointers themsef was not set to NULL, when shutting
down, meaning the next time used, NULL checks would not tell whether the
pointer is valid. This caused crashes ending with
#0  0x00007ffff73729e5 in raise () from /lib64/libc.so.6
#1  0x00007ffff735b895 in abort () from /lib64/libc.so.6
#2  0x00007ffff73b6857 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff73bdd7c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff73c2f1a in realloc () from /lib64/libc.so.6
#5  0x00007ffff78b558e in rfbSendOneRectEncodingZlib (cl=0x4a4b80, x=0, y=0, w=800, h=40) at /home/jonas/Dev/gnome/libvncserver/libvncserver/zlib.c:106
#6  0x00007ffff78b5dec in rfbSendRectEncodingZlib (cl=0x4a4b80, x=0, y=0, …

zlib: Clear buffer pointers on cleanup

---

libvncclient/rfbproto.c
rfb/rfbclient.h
rfb/rfbproto.h

This adds qemu extended key events to libvncclient, which greatly simplifies key event handling and improves robustness over the standard method.
An example of the new function call, `SendExtendedKeyEvent`, being used can be found here: https://github.com/any1/wlvncc/blob/qemu-extended-key-event/src/vnc.c#L215-L226
This functionality was tested using https://github.com/any1/wayvnc/tree/qemu-kb-ext & https://github.com/any1/neatvnc/tree/qemu-kb-ext.

libvncclient: Add qemu extended key event

---

libvncserver/rfbssl_gnutls.c
libvncserver/rfbssl_openssl.c

There is a small typo in libvncserver/rfbssl_gnutls.c, libvncserver/rfbssl_openssl.c.
Should read `functions` rather than `funtions`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, funtions -> functions

---

libvncserver/rfbserver.c

Fixes compiler warnings/errors:
```
libvncserver/rfbserver.c: In function 'rfbSendExtendedServerCutTextData':
libvncserver/rfbserver.c:2087:31: error: pointer targets in passing argument 1 of 'compress' differ in signedness [-Werror=pointer-sign]
if (compress(bufAfterZlib + 12, &size, bufBeforeZlib, len + 4) != Z_OK) {
~~~~~~~~~~~~~^~~~
In file included from rfb/rfbproto.h:73,
from rfb/rfb.h:44,
from libvncserver/rfbserver.c:37:
/usr/include/zlib.h:1228:21: note: expected 'Bytef *' {aka 'unsigned char *'} but argument is of type 'char *'
ZEXTERN int ZEXPORT compress OF((Bytef *dest,   uLongf *destLen,
^~~~~~~~
libvncserver/rfbserver.c:2087:44: error: pointer targets in passing argument 3 of 'compress' differ in signedness [-Werror=pointer-sign]
if (compress(bufAfterZlib + 12, &size, …
```

libvncserver: pass unsigned char pointers to zlib

---

examples/mac.c

Hi, thank you so much for the wonderful project!
I corrected a simple typo.

typo: permisssions → permissions

---

libvncclient/rfbproto.c
rfb/rfbproto.h

UltraVNC's MSLogonII protocol is relatively simple; the server sends along
DH parameters, we generate a shared secret, and we encrypt both the username
and password with it. The pubkey, username, and password then get written
back to the server.
Fixes #372

libvncclient: implement UltraVNC's MSLogonII authentication scheme

---

libvncserver/main.c
libvncserver/tightvnc-filetransfer/rfbtightserver.c
rfb/rfb.h
rfb/rfbregion.h

Add 'void' for few functions, as clang is not happy about fnc() instead of fnc(void). Small thing, but annoying.

clang-warning-fix

---

libvncserver/websockets.c
libvncserver/ws_decode.h

When htobe64 is a macro (FreeBSD) not having sys/endian.h in ws_decode.h results in a linker error.
I believe the same block can be removed from websockets.c since it includes ws_decode.h

libvncserver/ws_decode: include endian.h in ws_decode.h

---

libvncclient/cursor.c
libvncserver/cursor.c
libvncserver/hextile.c
libvncserver/selbox.c
libvncserver/tight.c

This fixes potential multiplication overflows caused by too late type promotion to size_t.

Fix potential multiplication overflows

---

libvncclient/rfbproto.c

Closes https://github.com/LibVNC/libvncserver/issues/505

Recognize UltraVnc and TightVNC server by security type

---

rfb/rfb.h

Move added rfbScreenInfo member to the end of the struct.
Fixes https://github.com/LibVNC/libvncserver/issues/507

libvncserver: fix ABI compatility with v0.9.13

---

libvncserver/websockets.c

In our libvcnserver-based application we once met a crash likely caused by a client issue - it has somehow sent and invalid handshake without a key. However, it's not a good idea for the server to crash in this key, we should return an error on such occasion and keep running.

Prevent crash on incomplete WebSocket handshake

---

libvncserver/sockets.c
libvncserver/websockets.c

The websocket code has internal buffers that expect data
not to be larger than UPDATE_BUF_SIZE
- Modify rfbWriteExact() to split larger writes in multiple
frames.
- Let webSocketsEncodeHybi() return -1 if somebody else
tries to pass a too large buffer to it.
(While in the libvncserver code rfbWriteExact() is the only
function that calls websocketEncode(), it is exposed by rfb.h,
so could theoretically also be called from application code)
Closes #484

websockets: fix buffer overflow in webSocketsEncodeHybi()

---

libvncserver/translate.c

Compare boolean truthiness only. The spec implies that only zero vs
non-zero matters.
This allows using no-conversion with e.g. jump desktop client. 
https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#setpixelformat

libvncserver: fix pixel format equality for different values of trueColour

---

client_examples/SDLvncviewer.c
libvncclient/rfbproto.c
libvncclient/vncviewer.c
rfb/rfbclient.h

This PR adds support for the client to request the server to change resolution and replace original https://github.com/LibVNC/libvncserver/pull/452 due inactivity of the author since Nov 2020.
Should resolve issue: https://github.com/LibVNC/libvncserver/issues/341
Tested with a future version of Remmina:
Initial size:
Resized only on X-axis:
Resized only on Y-axis:
Resized on both axis:
As you can see from images and from the output of xrandr command, it works!
Regards,
Marco

Dynamic resolution - support for SetDesktopSize in client

---

client_examples/vnc2mpg.c

Build fails with the master branch of FFmpeg with these kinds of errors:
```
../client_examples/vnc2mpg.c:55:5: error: unknown type name ‘AVCodecContext’
AVCodecContext *enc;
^~~~~~~~~~~~~~
``` 
This patch adds `libavcodec/avcodec.h` in vnc2mpg.c

Explicitely including avcodec.h

---

common/crypto_openssl.c

Fix the following build failure with libressl >= 3.5.0:
```
/nvmedata/autobuild/instance-26/output-1/build/libvncserver-0.9.13/common/crypto_openssl.c: In function 'dh_generate_keypair':
/nvmedata/autobuild/instance-26/output-1/build/libvncserver-0.9.13/common/crypto_openssl.c:149:7: error: dereferencing pointer to incomplete type 'DH' {aka 'struct dh_st'}
149 |     dh->p = BN_bin2bn(prime, keylen, NULL);
|       ^~
```
Fixes:
- http://autobuild.buildroot.org/results/49b3940b9d0432cb5fb0c5d22dfa017b18c6e233
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

common/crypto_openssl.c: fix build with libressl >= 3.5.0

---

libvncclient/sockets.c

man gethostbyname:
"The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror() functions are obsolete.  Applications should use getaddrinfo(3), getnameinfo(3), and gai_strerror(3) instead."

Replace gethostbyname() with getaddrinfo()

---

libvncclient/rfbproto.c
libvncclient/tls_gnutls.c
libvncclient/tls_openssl.c

Following https://github.com/LibVNC/libvncserver/issues/458
`rfbNoAuth` and `rfbVncAuth` are not actually part of VeNCrypt, however it is important to support them to ensure better compatibility. When establishing a connection, the client does not know whether the server supports encryption, and always prefers VeNCrypt if enabled. Next, if encryption is not available on the server, the connection will fail. Since the RFB doesn't have any downgrade methods in case of failure, a client that does not support unencrypted VeNCrypt methods will never be able to connect.
`rfbVeNCryptPlain` is also supported for better compatibility.
The [RFB specification also considers any ordinary subauths valid](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#vencrypt), which legitimizes this …

libvncclient: allow non-encrypted sub auth methods inside VeNCrypt

---

libvncclient/tls_gnutls.c

I.e. added ANON-ECDH just for better compatibility. Taken from TigerVNC: https://github.com/TigerVNC/tigervnc/blob/a97e9b11/common/rfb/CSecurityTLS.cxx#L210

libvncclient: rfbAnonTLSPriority = "NORMAL:+ANON-ECDH:+ANON-DH"

---

CMakeLists.txt
libvncclient/tls_gnutls.c

Following #525
Removed sleep, using `gnutls_handshake_set_timeout()` and `gnutls_system_recv_timeout()`. It's working since GNUTLS 3.4.0 (released 2015-04-08).
Found a solution here: https://github.com/gnutls/gnutls/blob/857543cc24114431dd5dde0e83c2c44b9b7e6050/lib/system/fastopen.c#L167
Also a loop without sleep seems to be the regular way to use GNUTLS according to github.

libvncclient: using gnutls_handshake_set_timeout()

---

libvncserver/cursor.c

This fixes random crashes in the cursor updating routines with VirtualBox 6.1.x running Ubuntu 22.04 guest when remote cursor is enabled (TightVNC client). 
The crash is as follows:
```
11/08/2022 11:58:59 Client Protocol Version 3.8
11/08/2022 11:58:59 Protocol version sent 3.8, using 3.8
11/08/2022 11:58:59 rfbProcessClientSecurityType: executing handler for type 2
11/08/2022 11:59:01 Enabling NewFBSize protocol extension for client 192.168.23.190
11/08/2022 11:59:01 Enabling LastRect protocol extension for client 192.168.23.190
11/08/2022 11:59:01 Enabling cursor position updates for client 192.168.23.190
11/08/2022 11:59:01 Enabling full-color cursor updates for client 192.168.23.190
11/08/2022 11:59:01 Using compression level 1 for client 192.168.23.190
11/08/2022 11:59:01 Using …
```

Make sure cursorMutex is properly locked before we try to access cursor member

---

libvncserver/tight.c
rfb/rfb.h

As of 7124b5fbcf0df8db4d3f73023d77af6ea56409e7 the maximum rect width and size are equal for every compression level so we can easily save the LUT entries by using constants instead.
This fixes OOB memory accesses in `rfbNumCodedRectsTight()` when being called by `rfbSendFramebufferUpdate()` before `SendRectEncodingTight()` is being called the first time (which limits `cl->tightCompressLevel` to the size of `tightConf`).

rfb.h cleanup + fix OOB memory accesses in tight encoder

---

common/crypto_openssl.c

Re: https://github.com/LibVNC/libvncserver/issues/493
Re: https://github.com/bk138/multivnc/issues/202
@bk138 , I would like to combine `dh_generate_keypair()` & `dh_compute_shared_key()` into a single function. We are doing a lot of unnecessary juggling by splitting these two.
- `DH` & `BIGNUM` objects are allocated, freed in `dh_generate_keypair()`,  and then reallocated again in `dh_compute_shared_key()`
- Storing DH private key outside of `DH` object is not needed. We simply copy it out of `dh_generate_keypair()` and pass to `dh_compute_shared_key()`
- Same situation is present in `crypto_libgrypt.c`

crypto: openssl: Pad DH key buffers with leading zeros for smaller keys

---

libvncserver/tableinittctemplate.c

Shifting a signed integer can result in undefined behavior.
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55190 cc @bk138

libvncserver: explicit cast before shift

---

libvncserver/tableinittctemplate.c

As it can turn into undefined behavior like
shift exponent 32 is too large for 32-bit type 'uint32_t'

libvncserver: check before shifting

---

.github/workflows/cifuzz.yml

CC @bk138 
This enables fuzzing on all Github PRs

ci: add CIFuzz workflow

---

src/libvncclient/rfbclient.c

Fix two minor type incompatibilities causing compiler errors when building with `-Werror`.

Libvncclient fixes

---

test/tjbench.c

If srcsize is an unsigned long, then the comparison (srcsize=ftell(file))<0 is always false.

test: Fix comparison that is always false

---

test/tjbench.c

This use of offset 'i' should follow the range check.

test: Fix offset used before range check

---

src/libvncserver/rfbserver.c

The webocket context was not free'd on client disconnect.

Fix memory leak on webclient disconnect

---

examples/server/pnmshow.c
examples/server/pnmshow24.c
test/bmp.c

Allocating memory with a size controlled by an external user can result in integer overflow.

Fix integer overflow in calculating allocation size

---

README.md

Due to changes in github and bk138/multivnc, it seems that the url is no longer available (github seems to have deleted the .rst rendering support and bk138/multivnc has added code since then).
This PR fixes the issue.

fix 'slow link' urls

---

src/common/crypto_openssl.c

Commit f135856fc3ce515afd16dbf91c44b89bab332726 added the same code to encrypt_rfbdes()

common/crypto_openssl: load legacy provider in decrypt_rfbdes()

---

src/libvncclient/tls_gnutls.c

Since GnuTLS 3.8, TTLS-SRP is disabled by default at compile time [1]. As a result, connecting to a server via TLS fails with:
> Warning: Failed to set TLS priority: The request is invalid. (+SRP).
> TLS handshake failed: No or insufficient priorities were set.
On the other hand, TLS-SRP is apparently unused in libvncclient. It seems TLS-SRP requires providing serveral parameters, including a username and a password, via specific GnuTLS API [2], which I didn't find in the codebase.
[1] https://gitlab.com/gnutls/gnutls/-/merge_requests/1681
[2] https://www.gnutls.org/manual/html_node/Authentication-using-SRP.html

libvncclient: improve compatibility with GnuTLS 3.8

---

include/rfb/rfb.h
src/libvncserver/main.c
src/libvncserver/rfbserver.c

A UTF-8 capable client will usually prefer to send cut-text via ExtendedClipboard encoding once libvncserver declares support for it. If app doesn't assign a setXCutTextUTF8() callback, the default handler is used which is no-op. So client-to-server clipboard transfer will not work.
Re: #638

Libvncserver: Enable ExtendedClipboard encoding only when app signals support for UTF-8 cut-text

---

src/libvncclient/rfbclient.c
src/libvncserver/rfbserver.c

1. According to spec, clipboard text is null terminated and text length includes the null byte. This is how LibVNCServer  and other clients encode this. Fixed by 2nd commit https://github.com/LibVNC/libvncserver/commit/7ff0a53d565b6f03380b08b89d05757be82b9c34
2. This is a big one. Many servers (including LibVNCServer) can't  properly handle zlib streams created by `compress()` function of zlib library. When decompressing such streams, `inflate()` correctly returns `Z_STREAM_END`, but these servers are only expecting `Z_OK`. So they end up crashing, while LibVNCserver abruptly disconnects  from client.
This is probably why the original PR #552 was not working. New PR simply suppressed it by adding extra byte, which made `inflate()` return `Z_OK`.
**Solution:**
- LibVNCServer is fixed by …

Fix Extended Clipboard implementation issues

---

src/libvncclient/cursor.c
src/libvncclient/rfbclient.c
src/libvncclient/tls_openssl.c
src/libvncclient/vncviewer.c
src/libvncserver/cursor.c
src/libvncserver/main.c
src/libvncserver/rfbserver.c
src/libvncserver/zrleoutstream.c
test/bmp.c
test/tjbench.c
test/tjunittest.c

I found several unnecessary checks for NULL before call of free().
I removed them.
I **don't** remove the check in code that sets the pointer to NULL after the free:
```
if(p)
{
free(p);
p = NULL;
}
```
Additionally I found a questionable macro FREE_IF in `main.c` which seems to be a shortcut to free (with unnecessary NULL check) a member of `struct screen`.  I renamed it to FREE_SCREEN_MEMBER to reflect its purpose better, but it is used only twice, so I'd favor to remove this macro completely.

remove unnecessary NULL checks before free()

---

CMakeLists.txt

CMake 4 dropped support for version requirements < 3.5.

CMake: Require at least CMake 3.5

---

src/libvncclient/listen.c

Listening uses a socket declared as a local variable, whereas accepting used an uninitialized client member variable. Note that the use of a local variable is necessary because the pointer to the client is invalid in the child process.
The problem was highlighted with x11vnc when running a VNC repeater (x11vnc -reflect listen:5500) waiting for an incoming connection from a VNC server (x11vnc -connect IP.ADDRESS.OF.REPEATER). When an incoming connection request was submitted, the repeater did not accept it and returned an error.

libvncserver: fix of listening for incoming connections
