libvncserver/rfbserver.c
Only advertise xvp support when xvpHook is set.
Prevents that clients such as novnc show "reboot" and "power down" buttons that are not going to work when pressed.
=> Only advertise xvp support when xvpHook is set

CMakeLists.txt
=> fixing SOVERSION and .so VERSION

ChangeLog, Doxyfile, NEWS, README, client_examples/vnc2mpg.c, common/zywrletemplate.c, examples/camera.c, libvncclient/listen.c, libvncclient/sockets.c, libvncserver/cargs.c, libvncserver/scale.c, libvncserver/sockets.c, libvncserver/tight.c, libvncserver/tightvnc-filetransfer/filetransfermsg.c, libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c, libvncserver/tightvnc-filetransfer/rfbtightproto.h, libvncserver/tightvnc-filetransfer/rfbtightserver.c, libvncserver/ultra.c, libvncserver/zlib.c, rfb/keysym.h, rfb/rfb.h, rfb/rfbproto.h, webclients/java-applet/ssl/README, webclients/java-applet/ssl/proxy.vnc, webclients/java-applet/ssl/ss_vncviewer, webclients/java-applet/ssl/ultravnc-102-JavaViewer-ssl-etc.patch, webclients/novnc/include/display.js, webclients/novnc/include/rfb.js, webclients/novnc/include/ui.js
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos (found by codespell)

libvncclient/rfbproto.c
https://github.com/LibVNC/libvncserver/issues/98
=> Ignore null pointers in FillRectangle() and CopyRectangleFromRectangle()

libvncclient/rfbproto.c
break statement was in the wrong line.
=> break statement out of case

rfb/rfbproto.h
I've set the maximum encodings count to 64, guess that should be more than enough.
=> Increase MAX_ENCODINGS value to accommodate more client encodings

common/md5.c, libvncserver/websockets.c, rfb/rfb.h, rfb/rfbclient.h
use different buffers for decode and encode
=> fix for issue 81

CMakeLists.txt, configure.ac, libvncserver/Makefile.am, libvncserver/sockets.c
Allows libvncserver sockets to be initialized from a systemd socket activated unit.
=> Support systemd socket activation

README, common/zywrletemplate.c, examples/example.c, examples/zippy.c, libvncserver/main.c, webclients/novnc/include/display.js, webclients/novnc/include/ui.js
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos

libvncserver/httpd.c
Fix for commit 65106d39627499ace4f1ed8701d3ab6c7f97f56f
Fixes #139
=> Write the correct length for end of header

libvncserver/rfbserver.c
Client-provided unsigned 32-bit cut text length is passed to various
functions that expects argument of a different type.
E.g. "RFB 003.003\n\001\006\0\0\0\xff\xff\xff\xff" string sent to the
RFB server leads to 4294967295 msg.cct.length value that in turn is
interpreted as -1 by rfbReadExact() and thus uninitialized str buffer
with potentially sensitive data is passed to subsequent functions.
This patch fixes it by checking for a maximal value that still can be
processed correctly. It also corrects accepting length value of zero
(malloc(0) is interpreted on differnet systems differently).
Whether a client can make the server allocate up to 2 GB and cause
a denial of service on memory-tight systems is kept without answer.
A possible solution would be adding an arbitrary memory limit that …
=> Validate client cut text length

libvncclient/trle.c
This pull request fix some warnings when build libvncclient
=> Fix warning

libvncserver/ws_decode.c
BUGFIX: Assuming the header is always a minimum of 14 Bytes long is not correct according to the RFC 6455 spec, it can be as short as 2 Bytes. Using it in combination with the RFB protocol, which tells that a client message can be as short as 6 Bytes, leads to reading past the end of a message. The proposal is to use WS_HYBI_HEADER_LEN_SHORT instead of WSHLENMAX to read only a minimum header, then reading the rest of the header if it is longer. Original finding here: https://github.com/LibVNC/libvncserver/issues/297
=> BUGFIX: use WS_HYBI_HEADER_LEN_SHORT instead of WSHLENMAX to read header

libvncserver/rfbssl_gnutls.c
=> LibVNCServer: Fix 'logical not is only applied to the..' warnings

libvncclient/tls_openssl.c
Similar to `SSL_read`/`SSL_write`, `SSL_get_error` uses the same SSL object (`client->tlsSession`)
and is not safe to call concurrently from different threads.
This is a followup from #389 .
---
@bk138 I read your comment somewhere and was wondering if you are still planning to refactor/cleanup the API for v1.x.x of LibVNC?
=> Move calls to `SSL_get_error` within mutex lock

common/vncauth.c, examples/colourmaptest.c, examples/cursors.c, examples/example.c, examples/fontsel.c, examples/pnmshow.c, examples/repeater.c, examples/rotatetemplate.c, examples/simple15.c, examples/vncev.c, libvncclient/rfbproto.c, libvncclient/sasl.c, libvncclient/vncviewer.c, libvncserver/cargs.c, libvncserver/corre.c, libvncserver/cursor.c, libvncserver/font.c, libvncserver/hextile.c, libvncserver/main.c, libvncserver/rfbregion.c, libvncserver/rfbserver.c, libvncserver/rre.c, libvncserver/selbox.c, libvncserver/tight.c, libvncserver/websockets.c
Always handle memory allocations failures + other minor fixes.
=> Add NULL pointer checks + other minor security improvements

.travis.yml
Hi,
I have added support for ppc64le build on travis-ci in the branch . The travis-ci build log can be tracked on the link :https://travis-ci.com/github/sanjay-cpu/libvncserver/builds/182311847 . I believe it is ready for the final review and merge.
Please have a look on it and if everything looks fine for you then please approve it for merge.
Thanks !!
=> TravisCI: add support for ppc64le

CMakeLists.txt, cmake/Modules/LibVNCServerConfig.cmake.in
Add the generation of cmake configuration files to apply to find_package
See: https://cmake.org/cmake/help/v3.20/manual/cmake-packages.7.html
=> CMake: Add the generation of cmake configuration files to apply to find_package

test/encodingstest.c
- rfbClientCleanup which is automatically in some failure scenarios
tries to interepret client data as rfbClientData
- sizeof char pointer vs array
=> test/encodingstest: fix some ASAN issues

examples/server/x11.c
`width` and `height` should be `uint16` rather than `int16_t`
=> fix typo: many type mismatch

common/crypto_openssl.c
DES encryption is considered legacy and is no longer available by default. To use it legacy provider must be load.
=> common/crypto_openssl.c: fix build with openssl >= 3.0.0

src/libvncclient/tight.c
When the host byte order of a client is different from that of the RFB pixel format it is using, we must swap bytes before delivering them to the client.  This commit addresses places where we were not properly doing that during tight decoding, manifesting in issues in which solid filled rectangles and gradients could be decoded to the wrong color.  As the RFB protocol spec says: "Swap the pixel value according to big-endian-flag (e.g. if big-endian-flag is zero (false) and host byte order is big endian, then swap)."
I have tested these changes on all combinations of (host byte order, pixel format byte order), namely (LE, LE), (LE, BE), (BE, LE), and (BE, BE).
Here are examples of the output before ![before](https://github.com/LibVNC/libvncserver/assets/24300095/13c1c99b-cdc8-46de-b662-8e0 …
=> libvncclient: fix tight decoding endianness issues

examples/client/qt5client.cpp
Resize the widget to after client init success; and the mouse events handle.
Log: add mouse events handle for Qt example.
=> examples: add mouse events handle for Qt example

src/libvncserver/httpd.c
This indicates that the HTTP server (httpd) crashed because the mutex (outputMutex) was not properly initialized before use.
=> fix: httpd service initialization issue #656.
